### PR TITLE
Prepare a release

### PR DESCRIPTION
**Pull request by bdewilde**
As discussed in https://github.com/dragnet-org/dragnet/issues/84

### CODE REVIEW

**Comment by bdewilde** [comment]
Just a friendly bump @pakelley — are you back and ready to hack? :)

**Comment by pakelley** [comment]
haha yep! I've been catching up on a couple things today, but I should have time to look at this either tonight or tomorrow!

**Comment by bdewilde** [comment]
Looks like I got a :shipit: — @pakelley , did you still want to take a look? If not, I'll just merge and see about publishing the minor release.

**Comment by pakelley** [comment]
nope, go ahead @bdewilde 👍

**Comment by pakelley** [comment]
was just looking, and it lgtm 🙂

**Comment by bdewilde** [comment]
For future reference: I forgot to bump the dependency versions in `setup.py` to match those now in `requirements.txt`. Will fix separately!

**Pull request merged**
